print("학과 입력 : ")
num1 = input()
print("이름 입력 : ")
num2 = input()
print("학번 입력 : ")
num3 = input()
print("-----------------------------------------")
print("학과 : " + num1)
print("이름 : " + num2)
print("학번 : " + num3)